### ISSUE TITLE
Scripts are Missing.

### ISSUE THREAD

**Issue by Zyankali** [Isti115/BlenderRenderController#10]
Hi, when i Download the Windows zip of your programm and than would like to Load a Blender File it just says. Scripts NOT found!

Well looks like i still figured it out by simple also download your script folder and insert it in the Folder where i have put in your program.

Should be in the ZIP file. So users don´t get to confused.

**Comment by isti115** [comment]
Hi! Thanks for your input! :) Which version did you download?
As far as I can see, the latest release (v0.4) includes the `Scripts` folder in the ZIP file:
https://github.com/Isti115/BlenderRenderController/releases/tag/0.4

**Comment by Zyankali** [comment]
you are right i was somehow getting that file...

BRC_v981_Full-x64.zip (i cant find anymore the reason why i was downloading that zip... well it´s midnight)

after following your link

yes the scripts are in. So that is all cool. But look! there is a new issue! ;(
