### ISSUE TITLE
jendabek 

### ISSUE THREAD

**Issue by red-rj** [Isti115/BlenderRenderController#6]
I just tried to use @jendabek 's fork Looks very cool and different! But I can't seem to get it to work.

It opens the .blend file just fine, reads all info, but when I click the render button nothing happends. Just quickly flashes some info about "X / Y chunks rendered" and says "Render Complete", but no files are created and Blender is never called.

I made sure my paths were correct (added some temp strings in MainForm.cs), manually created a `chunks` folder, tried some other things, to no avail :/

So @jendabek, am I missing something? Cause otherwise I liked what you did UI wise, like displaying all that new information 😉

**Comment by jendabek** [comment]
Oh, the problem is mainly I commit even the changes in the middle of work on something so I think thats the case. Please wait some hour / two and I will commit some tested work.
Thanks!

**Comment by red-rj** [comment]
I see, when you have a working commit let me know, I want to try merge some of my work (Like my Config paths) to your base, see if its posssible

**Comment by jendabek** [comment]
Please try the current commit. I have made some quick tests and it seems working fine. I would be happy for any feedback! Thanks

**Comment by red-rj** [comment]
Just tried the most recent commit and STILL does not work...

Same problem, read the info fine but no render occurs, I'm using Blender 2.78 and a recent ver. of FFmpeg

here's a vid of how it looks like to me:
https://drive.google.com/file/d/0B631HSUzwk1ycGlVTkdsRGVid2c/view?usp=sharing

UPDATE debugging shows the following exeption @ MainForm.cs line 363

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=Não é possível processar a solicitação porque o processo (5852) foi encerrado.
  Source=System
  StackTrace:
       em System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
       em System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
       em BlenderRenderController.MainForm.renderCurrentChunk() na C:\Users\Pedro\Source\Repos\BRC_jendabek\BlenderRenderController\BlenderRenderController\MainForm.cs:linha 363
       em BlenderRenderController.MainForm.updateProcessManagement(Object sender, EventArgs e) na C:\Users\Pedro\Source\Repos\BRC_jendabek\BlenderRenderController\BlenderRenderController\MainForm.cs:linha 560
       em System.Windows.Forms.Timer.OnTick(EventArgs e)
       em System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
       em System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       em System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       em System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       em System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       em System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       em System.Windows.Forms.Application.Run(Form mainForm)
       em BlenderRenderController.Program.Main() na C:\Users\Pedro\Source\Repos\BRC_jendabek\BlenderRenderController\BlenderRenderController\Program.cs:linha 19
       em System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       em System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       em Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       em System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

Blender never gets called to render the chunks, I double checked and my Blender path is valid

**Comment by jendabek** [comment]
Thank you, it is weird, I have tried it with 2.78a and 2.78b, now I downloaded 2.78 and it still works for me on 2 computers with different projects. It looks like Blender does not want to start the rendering so I suspect some issue with starting the Process (maybe some command line arguments...).
Can you please try the current commit and post me an error log which should be now (hopefully) saved to "log.txt" in the app directory?
THANK YOU!

**Comment by jendabek** [comment]
UPDATE: I get the problem. Stop testing please and wait for another commit :)

**Comment by jendabek** [comment]
FIXED. Now it will work :) The problem was it couldn't read file paths containing special characters like that space in your .blend name (thanks for that video!).
Please try it again and let me know.

**Comment by red-rj** [comment]
Yeah now it works, nice
