### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by GroundJet** [Isti115/BlenderRenderController#9]
I noticed there is not mention of a license anywhere I looked. Would appreciate to know under what license this program is.
Thank you.

**Comment by isti115** [comment]
Thank you for your interest, I will make sure to place a license file into the repository soon!
(I will have to look up what my options are.)

What are your plans with the code? :)

**Comment by isti115** [comment]
@GroundJet Sorry for being so slow, I have decided on the MIT license and added it to the project accordingly.

**Comment by GroundJet** [comment]
I'd like to prove to you that you can never be slower than the next guy, and I in this case am the next guy. I took over 10 days to reply to you because I was hoping I'd be able to code more seamless integration into Blender but looks like that is beyond my abilities, thanks anyway for the license.
